### ISSUE TITLE
PageSpeed Test

### ISSUE THREAD

**Issue by rleh** [TechAachen/Webseite-Jekyll#10]
https://developers.google.com/speed/pagespeed/insights/?hl=de&url=https%3A%2F%2Fpreview.techaachen.de%2Fv2%2F

**Comment by rleh** [comment]
Die Cache-Warnungen können/müssen für den Preview ignoriert werden. Caching ist für die Preview-Seite absichtlich im Server deaktiviert.

**Comment by lgirbig** [comment]
Sollte jetzt deutlich besser sein, habe die großen Bilder rausgeschmissen.
