### ISSUE TITLE
Feature: Terminliste direkt auf Webseite

### ISSUE THREAD

**Issue by mafficraft** [TechAachen/Webseite-Jekyll#37]
Moin zsm,

Die Terminliste ist ja aktuell nur als Kalender über iCal vorhanden. Eine Liste von kommenden Terminen direkt auf der Webseite wäre schön.

Darüber hinaus sucht niemand unter "Kontakt" den Link zum Kalender. das sollte ein zentraler Oberpunkt sein, damit man sofort sieht was den Verein ausmacht.

**Comment by rleh** [comment]
Sehr gute Idee! Hast du Lust das selbst anzupassen?

**Comment by rleh** [comment]
Ich hab da mal was angefangen: #39 

cc @mafficraft
